minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
overrides:
  '@aws-sdk/middleware-sdk-s3': 3.972.77
  '@aws-sdk/signature-v4-multi-region': 3.996.47
  postcss: 8.5.28
  string-width: 8.3.0
  brace-expansion@2: 2.1.7
allowBuilds:
  '@posthog/cli': true
  core-js: false
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
